### ISSUE TITLE
Automatically initializeApp on Firebase hosting

### ISSUE THREAD

**Issue by justweb1** [FirebaseExtended/polymerfire#221]
### Description
firebase-app should automatically initializeApp when being hosted on Firebase hosting. firebase-app should only have to be called like this:

```
<firebase-app name="optional"></firebase-app>
```

### Expected outcome
firebase-app element should pull properties from the Firebase hosting ENV variables.

### Actual outcome
Currently, dev has to create their own secrets or ENV variables.

**Comment by mbleigh** [comment]
This could be handled with an `auto` attribute that would go fetch the config from the reserved URL. However, that would be asynchronous which would make certain things difficult until we have a [solution for lazy loading](https://github.com/firebase/firebase-js-sdk/pull/15) in the JS SDK.

**Comment by justweb1** [comment]
@mbleigh I got this idea while watching one of your talks at I/O '17. I have been trying to figure out a solution. I think I might be close I'm going to put up a PR and try to get some help with it.

**Comment by justweb1** [comment]
Changed to stale
