### ISSUE TITLE
error on polymer build es6-bundled

### ISSUE THREAD

**Issue by Joel-hanson** [FirebaseExtended/polymerfire#236]
hi,
      i have developed a site with polymer 2.0 (portfolio site) and i found the i have been running into a error showing  
link of [image](https://goo.gl/photos/ks2BupG2rcnHkjsH7)
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at Ss.o.dispatchEvent ((index):23)
    at _s ((index):23)
    at Ss.wf ((index):23)
    at Ss.ne ((index):23)
```

but when i run without build it works perfectly the reason of the cause produces from line return `this.$.auth.signInWithPopup() `
i think that it is due to the `"js": {"minify": true},   "html": {"minify": true}` in polymer build.

**Comment by ava007** [comment]
I have the same issue.   see Login at  https://www.41max.com

**Comment by NicolasRannou** [comment]
+1

**Comment by Joel-hanson** [comment]
It comes from the js minify of polymer build so i removed it and done all the other minify like the html and css, and for js i used gulp minify-inline and gulp minify to reduce the size of the site. Even though it does not give that much of compression in inline js like the js minify in polymer build but it give a bit relief.

**Comment by alan-strohm** [comment]
I was able to work around this by reverting to version 2.0.0 of polymerfire.

**Comment by Joel-hanson** [comment]
+1

**Comment by oliver92** [comment]
+1

**Comment by chwzr** [comment]
Just open all files in the polymerfire folder with a -script ending.. and replace the imports with the ref from the google cdn..

```
<script src="https://www.gstatic.com/firebasejs/4.1.3/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/4.1.3/firebase-auth.js"></script>
<script src="https://www.gstatic.com/firebasejs/4.1.3/firebase-database.js"></script>
<script src="https://www.gstatic.com/firebasejs/4.1.3/firebase-messaging.js"></script>
```

each line in there own file..   now  minify does not minify the already minified firebase-scripts...
as an advantage you get faster page-load time because the scripts at cdn are g-zipped and pushed via http/2 I think.

**Comment by Joel-hanson** [comment]
it works but cannot give the efficiency of being a web app sending more request will cost more time and data.

**Comment by chwzr** [comment]
more data? It is smaller than the version in this repo plus it even uses only one request channel  and the browser caches that script - its only loaded once.   At mine it decreases the load time 0.1 second if I switch this lines to src at CDN.  The only bad is when you use it on a offline app ( like cordova  and you are offline...)

**Comment by ralcar** [comment]
Any fixes for this yet? This has been like this for a very long time now.

Using Polymer-CLI and choosing the starter kit with PRPL pattern, then just bower installing polymerfire and using the default example of <firebase-app> and <firebase-auth> does not work still, the most simplest of actions to get started.

Right now I have to do js: {minify:false} in polymer.json, and then add the line "navigateFallbackWhitelist: [/^(?!\/__)/]" in sw-precache-config.js just to get a site running on firebase.

How are not more people getting stopped in the first step by this? Finding these threads and doing workarounds should not be a requirement just to get the first step of Polymer + Firebase +Polymerfire working.

Sorry for the tone, just a bit surprised that this is not fixed yet. I really want Polymer/Firebase/Polymerfire to grow so i can make my job move over to it :D

**Comment by Protoss78** [comment]
Having the same problem. Thanks for the workaround.

**Comment by eduardosada** [comment]
I have the same problem and using the CDN is not an option for me :(

**Comment by arcodebonte** [comment]
Also the workarounds doesn't solve the problem for me :-(

**Comment by unionthugface** [comment]
Any movement on this?

**Comment by tjmonsi** [comment]
The problem here really is that (if I guess it right) minify deletes part of the code that is needed in Firebase. Best bet is to ask the guys in the firebase team in the firebase repo to check on this.

@mbleigh ? Who can we ask?

**Comment by christophe-g** [comment]
this [PR](https://github.com/Polymer/polymer-cli/pull/878) might solve the problem. It allows to skip minification for problematic files.

You might need to compile polymer-cli from source after pulling the branch.

**Comment by tjmonsi** [comment]
@christophe-g thanks for that. This would solve a lot more than firebase scripts (I had problems with some other files as well before)
