### ISSUE TITLE
connectedCallback is not invoked when FirestoreMixin is applied multiple times

### ISSUE THREAD

**Issue by merlinnot** [FirebaseExtended/polymerfire#323]
Given

```js
class extends Polymer.FirestoreMixin(Polymer.FirestoreMixin(otherMixin(Polymer.Element))) {}
```

`connectedCallback` in `otherMixin` won't be invoked.

**Comment by tjmonsi** [comment]
can we have a small repo to work on to see?

**Comment by merlinnot** [comment]
Sorry, I've made a fix for this the same day, just forgot to mention it.

**Comment by merlinnot** [comment]
I'm leaving this one open since it's not in the master yet, as all other issues.

**Comment by tjmonsi** [comment]
I see. Thanks :)
